In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [41]:
dataset = pd.read_excel('FINAL.CSV.xlsx')
X = dataset.iloc[:5000, [11,12,23,25,15]].values
y = dataset.iloc[:5000, 28].values
print(X)

[[1 0 0 1 1]
 [0 1 1 1 1]
 [1 1 0 0 2]
 ...
 [0 0 0 1 3]
 [1 1 1 1 2]
 [0 1 1 0 1]]


In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)


In [55]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [56]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [57]:
y_pred = classifier.predict(X_test)


In [58]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[307, 193],
       [292, 208]])

In [59]:
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.515
